on:
  schedule:
    - cron:  '0 * * * *' # Hourly. Ref https://crontab.guru/examples.html
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
name: Pull from Airtable
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      run: yarn install
    - name: Extract
      run: yarn run pull:airtable
      env:
        AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
    - name: Transform
      run: yarn run transform:data
    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you
